/**
 * M65816: Portable 65816 Emulator
 * Written and Copyright (C) 1996 - 2016 by Joshua M. Thompson
 *
 * You are free to distribute this code for non-commercial purposes
 * I ask only that you notify me of any changes you make to the code
 * Commercial use is prohibited without my written permission
 */

const int kLenIsMemorySize = -1;
const int kLenIsIndexSize  = -2;

// Addressing modes

const unsigned int kAddrMode_immediate   = 1;
const unsigned int kAddrMode_a           = 2;
const unsigned int kAddrMode_al          = 3;
const unsigned int kAddrMode_d           = 4;
const unsigned int kAddrMode_accumulator = 5;
const unsigned int kAddrMode_implied     = 6;
const unsigned int kAddrMode_dix         = 7;
const unsigned int kAddrMode_dixl        = 8;
const unsigned int kAddrMode_dxi         = 9;
const unsigned int kAddrMode_dxx         = 10;
const unsigned int kAddrMode_dxy         = 11;
const unsigned int kAddrMode_axx         = 12;
const unsigned int kAddrMode_alxx        = 13;
const unsigned int kAddrMode_axy         = 14;
const unsigned int kAddrMode_pcr         = 15;
const unsigned int kAddrMode_pcrl        = 16;
const unsigned int kAddrMode_ai          = 17;
const unsigned int kAddrMode_ail         = 171; // same as _ai in the data sheet but acts differently
const unsigned int kAddrMode_di          = 18;
const unsigned int kAddrMode_dil         = 19;
const unsigned int kAddrMode_axi         = 20;
const unsigned int kAddrMode_stack       = 21;
const unsigned int kAddrMode_sr          = 22;
const unsigned int kAddrMode_srix        = 23;
const unsigned int kAddrMode_blockmove   = 24;

struct opcode {
    const unsigned char mnemonic[4];
    const unsigned int mode;
    const int len;
};

const opcode opcodes[256] = {
    {"BRK", kAddrMode_implied,     1                },
    {"ORA", kAddrMode_dxi,         2                },
    {"COP", kAddrMode_implied,     1                },
    {"ORA", kAddrMode_sr,          2                },
    {"TSB", kAddrMode_d,           2                },
    {"ORA", kAddrMode_d,           2                },
    {"ASL", kAddrMode_d,           2                },
    {"ORA", kAddrMode_dil,         2                },
    {"PHP", kAddrMode_implied,     1                },
    {"ORA", kAddrMode_immediate,   kLenIsMemorySize },
    {"ASL", kAddrMode_accumulator, 1                },
    {"PHD", kAddrMode_implied,     1                },
    {"TSB", kAddrMode_a,           3                },
    {"ORA", kAddrMode_a,           3                },
    {"ASL", kAddrMode_a,           3                },
    {"ORA", kAddrMode_al,          4                },
    {"BPL", kAddrMode_pcr,         2                },
    {"ORA", kAddrMode_dix,         2                },
    {"ORA", kAddrMode_di,          2                },
    {"ORA", kAddrMode_srix,        2                },
    {"TRB", kAddrMode_d,           2                },
    {"ORA", kAddrMode_dxx,         2                },
    {"ASL", kAddrMode_dxx,         2                },
    {"ORA", kAddrMode_dixl,        2                },
    {"CLC", kAddrMode_implied,     1                },
    {"ORA", kAddrMode_axy,         3                },
    {"INC", kAddrMode_accumulator, 1                },
    {"TCS", kAddrMode_implied,     1                },
    {"TRB", kAddrMode_a,           3                },
    {"ORA", kAddrMode_axx,         3                },
    {"ASL", kAddrMode_axx,         3                },
    {"ORA", kAddrMode_alxx,        4                },
    {"JSR", kAddrMode_a,           3                },
    {"AND", kAddrMode_dxi,         2                },
    {"JSL", kAddrMode_al,          4                },
    {"AND", kAddrMode_sr,          2                },
    {"BIT", kAddrMode_d,           2                },
    {"AND", kAddrMode_d,           2                },
    {"ROL", kAddrMode_d,           2                },
    {"AND", kAddrMode_dil,         2                },
    {"PLP", kAddrMode_implied,     1                },
    {"AND", kAddrMode_immediate,   kLenIsMemorySize },
    {"ROL", kAddrMode_accumulator, 1                },
    {"PLD", kAddrMode_implied,     1                },
    {"BIT", kAddrMode_a,           3                },
    {"AND", kAddrMode_a,           3                },
    {"ROL", kAddrMode_a,           3                },
    {"AND", kAddrMode_al,          4                },
    {"BMI", kAddrMode_pcr,         2                },
    {"AND", kAddrMode_dix,         2                },
    {"AND", kAddrMode_di,          2                },
    {"AND", kAddrMode_srix,        2                },
    {"BIT", kAddrMode_dxx,         2                },
    {"AND", kAddrMode_dxx,         2                },
    {"ROL", kAddrMode_dxx,         2                },
    {"AND", kAddrMode_dixl,        2                },
    {"SEC", kAddrMode_implied,     1                },
    {"AND", kAddrMode_axy,         3                },
    {"DEC", kAddrMode_accumulator, 1                },
    {"TSC", kAddrMode_implied,     1                },
    {"BIT", kAddrMode_axx,         3                },
    {"AND", kAddrMode_axx,         3                },
    {"ROL", kAddrMode_axx,         3                },
    {"AND", kAddrMode_alxx,        4                },
    {"RTI", kAddrMode_implied,     1                },
    {"EOR", kAddrMode_dxi,         2                },
    {"WDM", kAddrMode_immediate,   2                },
    {"EOR", kAddrMode_sr,          2                },
    {"MVN", kAddrMode_blockmove,   3                },
    {"EOR", kAddrMode_d,           2                },
    {"LSR", kAddrMode_d,           2                },
    {"EOR", kAddrMode_dil,         2                },
    {"PHA", kAddrMode_implied,     1                },
    {"EOR", kAddrMode_immediate,   kLenIsMemorySize },
    {"LSR", kAddrMode_accumulator, 1                },
    {"PHK", kAddrMode_implied,     1                },
    {"JMP", kAddrMode_a,           3                },
    {"EOR", kAddrMode_a,           3                },
    {"LSR", kAddrMode_a,           3                },
    {"EOR", kAddrMode_al,          4                },
    {"BVC", kAddrMode_pcr,         2                },
    {"EOR", kAddrMode_dix,         2                },
    {"EOR", kAddrMode_di,          2                },
    {"EOR", kAddrMode_srix,        2                },
    {"MVN", kAddrMode_blockmove,   3                },
    {"EOR", kAddrMode_dxx,         2                },
    {"LSR", kAddrMode_dxx,         2                },
    {"EOR", kAddrMode_dixl,        2                },
    {"CLI", kAddrMode_implied,     1                },
    {"EOR", kAddrMode_axy,         3                },
    {"PHY", kAddrMode_implied,     1                },
    {"TCD", kAddrMode_implied,     1                },
    {"JMP", kAddrMode_al,          4                },
    {"EOR", kAddrMode_axx,         3                },
    {"LSR", kAddrMode_axx,         3                },
    {"EOR", kAddrMode_alxx,        4                },
    {"RTS", kAddrMode_implied,     1                },
    {"ADC", kAddrMode_dxi,         2                },
    {"PER", kAddrMode_pcrl,        3                },
    {"ADC", kAddrMode_sr,          2                },
    {"STZ", kAddrMode_d,           2                },
    {"ADC", kAddrMode_d,           2                },
    {"ROR", kAddrMode_d,           2                },
    {"ADC", kAddrMode_dil,         2                },
    {"PLA", kAddrMode_implied,     1                },
    {"ADC", kAddrMode_immediate,   kLenIsMemorySize },
    {"ROR", kAddrMode_accumulator, 1                },
    {"RTL", kAddrMode_implied,     1                },
    {"JMP", kAddrMode_ai,          3                },
    {"ADC", kAddrMode_a,           3                },
    {"ROR", kAddrMode_a,           3                },
    {"ADC", kAddrMode_al,          4                },
    {"BVS", kAddrMode_pcr,         2                },
    {"ADC", kAddrMode_dix,         2                },
    {"ADC", kAddrMode_di,          2                },
    {"ADC", kAddrMode_srix,        2                },
    {"STZ", kAddrMode_dxx,         2                },
    {"ADC", kAddrMode_dxx,         2                },
    {"ROR", kAddrMode_dxx,         2                },
    {"ADC", kAddrMode_dixl,        2                },
    {"SEI", kAddrMode_implied,     1                },
    {"ADC", kAddrMode_axy,         3                },
    {"PLY", kAddrMode_implied,     1                },
    {"TDC", kAddrMode_implied,     1                },
    {"JMP", kAddrMode_axi,         3                },
    {"ADC", kAddrMode_axx,         3                },
    {"ROR", kAddrMode_axx,         3                },
    {"ADC", kAddrMode_alxx,        4                },
    {"BRA", kAddrMode_pcr,         2                },
    {"STA", kAddrMode_dxi,         2                },
    {"BRL", kAddrMode_pcrl,        3                },
    {"STA", kAddrMode_sr,          2                },
    {"STY", kAddrMode_d,           2                },
    {"STA", kAddrMode_d,           2                },
    {"STX", kAddrMode_d,           2                },
    {"STA", kAddrMode_dil,         2                },
    {"DEY", kAddrMode_implied,     1                },
    {"BIT", kAddrMode_immediate,   kLenIsMemorySize },
    {"TXA", kAddrMode_implied,     1                },
    {"PHB", kAddrMode_implied,     1                },
    {"STY", kAddrMode_a,           3                },
    {"STA", kAddrMode_a,           3                },
    {"STX", kAddrMode_a,           3                },
    {"STA", kAddrMode_al,          4                },
    {"BCC", kAddrMode_pcr,         2                },
    {"STA", kAddrMode_dix,         2                },
    {"STA", kAddrMode_di,          2                },
    {"STA", kAddrMode_srix,        2                },
    {"STY", kAddrMode_dxx,         2                },
    {"STA", kAddrMode_dxx,         2                },
    {"STX", kAddrMode_dxy,         2                },
    {"STA", kAddrMode_dixl,        2                },
    {"TYA", kAddrMode_implied,     1                },
    {"STA", kAddrMode_axy,         3                },
    {"TXS", kAddrMode_implied,     1                },
    {"TXY", kAddrMode_implied,     1                },
    {"STZ", kAddrMode_a,           3                },
    {"STA", kAddrMode_axx,         3                },
    {"STZ", kAddrMode_axx,         3                },
    {"STA", kAddrMode_alxx,        4                },
    {"LDY", kAddrMode_immediate,   kLenIsIndexSize  },
    {"LDA", kAddrMode_dxi,         2                },
    {"LDX", kAddrMode_immediate,   kLenIsIndexSize  },
    {"LDA", kAddrMode_sr,          2                },
    {"LDY", kAddrMode_d,           2                },
    {"LDA", kAddrMode_d,           2                },
    {"LDX", kAddrMode_d,           2                },
    {"LDA", kAddrMode_dil,         2                },
    {"TAY", kAddrMode_implied,     1                },
    {"LDA", kAddrMode_immediate,   kLenIsMemorySize },
    {"TAX", kAddrMode_implied,     1                },
    {"PLB", kAddrMode_implied,     1                },
    {"LDY", kAddrMode_a,           3                },
    {"LDA", kAddrMode_a,           3                },
    {"LDX", kAddrMode_a,           3                },
    {"LDA", kAddrMode_al,          4                },
    {"BCS", kAddrMode_pcr,         2                },
    {"LDA", kAddrMode_dix,         2                },
    {"LDA", kAddrMode_di,          2                },
    {"LDA", kAddrMode_srix,        2                },
    {"LDY", kAddrMode_dxx,         2                },
    {"LDA", kAddrMode_dxx,         2                },
    {"LDX", kAddrMode_dxy,         2                },
    {"LDA", kAddrMode_dixl,        2                },
    {"CLV", kAddrMode_implied,     1                },
    {"LDA", kAddrMode_axy,         3                },
    {"TSX", kAddrMode_implied,     1                },
    {"TYX", kAddrMode_implied,     1                },
    {"LDY", kAddrMode_axx,         3                },
    {"LDA", kAddrMode_axx,         3                },
    {"LDX", kAddrMode_axy,         3                },
    {"LDA", kAddrMode_alxx,        4                },
    {"CPY", kAddrMode_immediate,   kLenIsIndexSize  },
    {"CMP", kAddrMode_dxi,         2                },
    {"REP", kAddrMode_immediate,   2                },
    {"CMP", kAddrMode_sr,          2                },
    {"CPY", kAddrMode_d,           2                },
    {"CMP", kAddrMode_d,           2                },
    {"DEC", kAddrMode_d,           2                },
    {"CMP", kAddrMode_dil,         2                },
    {"INY", kAddrMode_implied,     1                },
    {"CMP", kAddrMode_immediate,   kLenIsMemorySize },
    {"DEX", kAddrMode_implied,     1                },
    {"WAI", kAddrMode_implied,     1                },
    {"CPY", kAddrMode_a,           3                },
    {"CMP", kAddrMode_a,           3                },
    {"DEC", kAddrMode_a,           3                },
    {"CMP", kAddrMode_al,          4                },
    {"BNE", kAddrMode_pcr,         2                },
    {"CMP", kAddrMode_dix,         2                },
    {"CMP", kAddrMode_di,          2                },
    {"CMP", kAddrMode_srix,        2                },
    {"PEI", kAddrMode_d,           2                },
    {"CMP", kAddrMode_dxx,         2                },
    {"DEC", kAddrMode_dxx,         2                },
    {"CMP", kAddrMode_dixl,        2                },
    {"CLD", kAddrMode_implied,     1                },
    {"CMP", kAddrMode_axy,         3                },
    {"PHX", kAddrMode_implied,     1                },
    {"STP", kAddrMode_implied,     1                },
    {"JML", kAddrMode_ail,         3                },
    {"CMP", kAddrMode_axx,         3                },
    {"DEC", kAddrMode_axx,         3                },
    {"CMP", kAddrMode_alxx,        4                },
    {"CPX", kAddrMode_immediate,   kLenIsIndexSize  },
    {"SBC", kAddrMode_dxi,         2                },
    {"SEP", kAddrMode_immediate,   2                },
    {"SBC", kAddrMode_sr,          2                },
    {"CPX", kAddrMode_d,           2                },
    {"SBC", kAddrMode_d,           2                },
    {"INC", kAddrMode_d,           2                },
    {"SBC", kAddrMode_di,          2                },
    {"INX", kAddrMode_implied,     1                },
    {"SBC", kAddrMode_immediate,   kLenIsMemorySize },
    {"NOP", kAddrMode_implied,     1                },
    {"XBA", kAddrMode_implied,     1                },
    {"CPX", kAddrMode_a,           3                },
    {"SBC", kAddrMode_a,           3                },
    {"INC", kAddrMode_a,           3                },
    {"SBC", kAddrMode_al,          4                },
    {"BEQ", kAddrMode_pcr,         2                },
    {"SBC", kAddrMode_dix,         2                },
    {"SBC", kAddrMode_di,          2                },
    {"SBC", kAddrMode_srix,        2                },
    {"PEA", kAddrMode_immediate,   3                },
    {"SBC", kAddrMode_dxx,         2                },
    {"INC", kAddrMode_dxx,         2                },
    {"SBC", kAddrMode_dixl,        2                },
    {"SED", kAddrMode_implied,     1                },
    {"SBC", kAddrMode_axy,         3                },
    {"PLX", kAddrMode_implied,     1                },
    {"XCE", kAddrMode_implied,     1                },
    {"JSR", kAddrMode_axi,         3                },
    {"SBC", kAddrMode_axx,         3                },
    {"INC", kAddrMode_axx,         3                },
    {"SBC", kAddrMode_alxx,        4                },
};
